 <body>
	 
	 
	  <button id="scrollToBottomBtn">Scroll to Bottom</button>

    <script src="_js/scroll.js">
	 
	
	 
	 </script>
	 
	 
	 
	 
	 
<div class="top-container"> <img class="top-cloud" src="images/Clouds.png" alt="Clouds-img">
  <h1>I'm Joshua</h1>
  <h3 class="screen-name">GraveYardJokes</h3>
  <h2>a <span class="underlined">Musician</span> and <span class="underlined">Website Developer</span></h2>
  <img class="bottom-cloud" src="images/Clouds.png" alt="Clouds-img"> <img class="Mountains" src="images/Mountains.png" alt="Mountains-img"> </div>
<div class="middle-container">
  <div class="profile"> <img src="images/GraveYardJokesLogoJesterWhiteBacking.svg" alt="profile-picture" width="20%" height="auto">
    <h2>Hello.</h2>
    <p class="intro">I am a multi-talented individual, proficient in web development, art, design, and music. With a thoughtful approach to each project, I bring a unique blend of skills and creativity to deliver exceptional results.</p>
  </div>
  <hr>
  <div class="skills">
    <h2>My Skills.</h2>
    <div class="skill-row"><img class="Gear-img" src="images/Gears.png" alt="Gears-Pic">
      <h3>Programming</h3>
      <p class="Gear-par">"Welcome! I have a strong background in game development, having worked extensively with the Unity game engine and mastered the art of C#. Additionally, I bring expertise in web design, specializing in HTML, CSS, and Javascript. With a passion for both gaming and web development, I'm dedicated to crafting immersive experiences and creating visually stunning websites. Join me on this exciting journey as we bring your ideas to life and leave a lasting impact on the digital world!"</p>
    </div>
    <div class="skill-row"> <img class="Note-img" src="images/Notes.png" alt="Notes-Pic">
      <h3>Music</h3>
      <p class="Note-par">"Welcome! I am an accomplished musician with expertise in guitar and piano. My musical journey has led me to create a diverse repertoire of original compositions and collaborate with various bands. Equipped with my own professional-grade equipment, I possess the power to bring music to life in my personal studio. Whether it's crafting soulful melodies or igniting an energetic rhythm, I'm dedicated to delivering captivating musical experiences. Join me on this melodic adventure as we create harmonies that resonate with hearts and leave a lasting impact on ears. Let's make music together!"</p>
    </div>
    <div class="skill-row"> <img class="Art-img" src="images/Art.png" alt="Art-Pic">
      <h3>Digital Art</h3>
      <p class="Art-par"> "Embracing my innate artistic spirit, I have embarked on a creative journey dedicated to crafting captivating graphics. With a keen interest in animation and digital art, I channel my passion into bringing visual ideas to life. Through meticulous attention to detail and an imaginative approach, I strive to create visually stunning and engaging experiences. Join me on this artistic expedition as we explore new horizons, merging creativity and technology to leave a lasting impression. Let's unleash the power of visuals together!"</p>
    </div>
  </div>
  <hr>
  <div class="contact-me">
    <h2>Get In Touch</h2>
    <h3 class="ava-txt">I'm avalable for freelance work for Web Design, for composing music, or to create digital art for any number of reasons.</h3>
    <p>Negotiate your terms with me <br> over a coffee. <br>☕</p>
    <a class="btn" href="mailto:GraveYardJokes@gmail.com">CONTACT ME</a> </div>
  <div>
	  
	  
	  <div class="portfolio">
	<h2>Portfolio</h2>
	<ul>
		<li><a href="https://graveyardjokes.com/ChaoticWeather/home.html#&panel1-3">Chaotic Weather</a></li>
		<li><a href="https://graveyardjokes.com/WBG410/home.php">My Gaming Site</a></li>
		<li><a href="https://graveyardjokes.com/WGD251/">Air Guitar Pro</a></li>
        <li><a href="https://joshua050.mystrikingly.com">About</a></li>
	</ul>
  </div>
	  
	  
	  <br>
	  <br>
	  
<iframe frameborder="0" src="https://itch.io/embed/1493786?border_width=5&amp;bg_color=0ea644&amp;fg_color=c2d940&amp;link_color=5be5fa&amp;border_color=000000" width="560" height="175"><a href="https://graveyardjokes.itch.io/skull-run">Crypt Escape: A Skeleton's Journey by GraveYardJokes</a></iframe></div>

  

  </div>
</body>
